export const CHARACTER_STATES = {
    IDLE_STATE: 'IDLE_STATE',
    MOVE_STATE: 'MOVE_STATE',
    BOUNCE_MOVE_STATE: 'BOUNCE_MOVE_STATE',
    HURT_STATE: 'HURT_STATE',
    DEATH_STATE: 'DEATH_STATE',
    
}as const;